// Day 18/Twitter Clone Task/src/App.jsx
import './App.css';
import React, {useState,useEffect} from 'react';
import Tweets from "./Tweeter/Tweets";

const App = () => {
    const [info, setinfo] = useState({
        fname:"",
        lname:"",
        age:0
    });
    const handleClick=(event)=>{
        event.preventDefault();
        console.log(info);
    }
    const handleFname=(event)=>{
        console.log(event.target.value);
        setinfo({...info,fname:event.target.value});
    }
    const handleLname=(event)=>{
        console.log(event.target.value);
        setinfo({...info,lname:event.target.value})
    }
    const handleAge=(event)=>{
        console.log(event.target.value);
        setinfo({...info,age:event.target.value})
    }
return( <>
<form action="">
    <input type="text" placeholder='Enter First name' onChange={handleFname} value={info.fname}/>
    <input type="text" placeholder='Enter Last Name' onChange={handleLname} value={info.lname}/>
    <input type="number" placeholder='Enter age' onChange={handleAge} value={info.age}/>
    <button onClick={handleClick}>Click Me</button>
</form>
{/* <Tweets></Tweets> */}
</>
);

}

export default App

// Day 13/Template Form Validation Basics/src/app/app.component.ts
import { style } from '@angular/animations';
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'MyApp';
  signin(login:any){
    console.log(login);
  }
}

<!-- Template Form -->

<form action="" #login="ngForm" (ngSubmit)="signin(login)">
    <input type="text" name="fname" placeholder="Enter First Name" #fname="ngModel" minlength="4" ngModel>
    <small *ngIf="fname.invalid" id="error">Please Enter Valid Name</small>
    <input type="text" name="lname" placeholder="Enter Last Name" #lname="ngModel" minlength="4" ngModel>
    <small *ngIf="lname.invalid" id="error">Please Enter Valid Name</small>
    <input type="password" name="pass" placeholder="Enter Password" #pass="ngModel" ngModel>
    <small *ngIf="pass.invalid" id="error">Please Enter Valid Password</small>
    <button type="submit" [disabled]="!login.valid">Sign In</button>
</form>
